services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db              
      - DB_PORT=5432            
      - DB_USERNAME=paulo       
      - DB_PASSWORD=123         
      - DB_DATABASE=postgres    
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=paulo     
      - POSTGRES_PASSWORD=123   
      - POSTGRES_DB=postgres    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: