### list products
GET http://localhost:3000/products

### get product
GET http://localhost:3000/products/market_AJVgCarxe3hruT0kUrE0e

### create product
POST http://localhost:3000/orders
Content-Type: application/json

{
   "products": [{
    "id": "market_U0v-5rhtnBNHbbh_G-gQI",
    "name": "Panela Inox",
    "category": "utensílios domésticos",
    "description": "produto simples",
    "quantity": 4,
    "price": 253
  }],
    "total_orders": 2,
    "status": "Concluído"
}

### update product
PATCH http://localhost:3000/products/market_AJVgCarxe3hruT0kUrE0e
Content-Type: application/json

{
    "quantity": 34
}

### delete product
DELETE http://localhost:3000/products/market_nnntoB_Y3q4HvHMuE23Yn